import { translate } from "@/i18n";
import { ProjectInterface, ServiceOfferInterface } from "./types";
import * as url from "./url";
import { NavLinkInterface, SocialMediaLinksInterface } from "@/screens";
import * as Stack from "./stack";

export const NAV_LINKS: NavLinkInterface[] = [
  {
    name: translate("header.navLinks.services"),
    path: "#services",
    selectedId: "services",
  },
  {
    name: translate("header.navLinks.projects"),
    path: "#projects",
    selectedId: "projects",
  },
  {
    name: translate("header.navLinks.contacts"),
    path: "#contacts",
    selectedId: "contacts",
  },
];

export const SOCIAL_MEDIA_LINKS: SocialMediaLinksInterface[] = [
  {
    key: "github",
    icon: "fa6-brands:square-github",
    title: translate("header.socialMediaLinks.github"),
    url: url.GITHUB_URL,
  },
  {
    key: "linkedIn",
    icon: "fa6-brands:linkedin",
    title: translate("header.socialMediaLinks.linkedIn"),
    url: url.LINKED_IN_URL,
  },
  {
    key: "upwork",
    icon: "fa6-brands:upwork",
    title: translate("header.socialMediaLinks.upwork"),
    url: url.UPWORK_URL,
  },
];

export const SERVICE_OFFER: ServiceOfferInterface[] = [
  {
    title: translate("services.backend.title"),
    description: translate("services.backend.description"),
    stack: [
      Stack.SPRING_BOOT_STACK,
      Stack.SPRING_SECURITY_STACK,
      Stack.SPRING_OAUTH_STACK,
      Stack.SPRING_JDBC_STACK,
      Stack.SPRING_API_STACK,
      Stack.JAVA_STACK,
      Stack.MYSQL_STACK,
      Stack.JUNIT_STACK,
      Stack.MOCKITO_STACK,
      Stack.POSTMAN_STACK,
      Stack.LINUX_STACK,
      Stack.AZURE_STACK,
      Stack.AWS_STACK,
      Stack.AZURE_PIPELINE_AGENT_STACK,
      Stack.FIREBASE_STACK,
      Stack.GIT_STACK,
      Stack.NGINX_STACK,
      Stack.CENTOS_STACK,
      Stack.NETLIFY_STACK,
      Stack.HEROKU_STACK,
    ],
  },
  {
    title: translate("services.frontend.title"),
    description: translate("services.frontend.description"),
    stack: [
      Stack.VITE_STACK,
      Stack.REACT_STACK,
      Stack.TYPESCRIPT_STACK,
      Stack.JAVASCRIPT_STACK,
      Stack.HTML_STACK,
      Stack.CSS_STACK,
      Stack.JQUERY_STACK,
      Stack.BLADE_STACK,
      Stack.TAILWIND_STACK,
      Stack.SHAD_CN_STACK,
      Stack.MUI_STACK,
      Stack.CHAKRA_STACK,
      Stack.ANT_DESIGN_STACK,
      Stack.NEXT_UI_STACK,
      Stack.ZUSTAND_STACK,
      Stack.MOBX_STACK,
      Stack.CHART_JS_STACK,
      Stack.GSAP_STACK,
      Stack.THREE_JS_STACK,
      Stack.FRAMER_MOTION_STACK,
      Stack.CYPRESS_STACK,
      Stack.I18N_STACK,
      Stack.AXIOS_STACK,
      Stack.REACT_QUERY_STACK,
      Stack.NPM_STACK,
      Stack.PNPM_STACK,
      Stack.YARN_STACK,
    ],
  },
  {
    title: translate("services.designImplementation.title"),
    description: translate("services.designImplementation.description"),
    stack: [
      Stack.FIGMA_STACK,
      Stack.FRONTEND_STACK,
      Stack.FIGMA_TO_HTML_STACK,
      Stack.FIGMA_TO_REACT_STACK,
      Stack.ATTENTION_TO_DETAILS_STACK,
      Stack.PIXEL_PERFECT_STACK,
      Stack.LANDING_PAGE_STACK,
    ],
  },
];

export const PROJECTS: ProjectInterface[] = [
  {
    title: "YooPH",
    company: "Mach95 Software Developer Corp.",
    date: new Date(),
    description: translate("projects.yoo.description"),
    category: ["delivery app", "ecommerce", "admin dashboard"],
    previewUrl: "https://www.yoo.ph/login",
    codeUrl: undefined,
    type: "confidential",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: "Yoo PH Preview",
    stack: [
      Stack.LARAVEL_STACK,
      Stack.PHP_STACK,
      Stack.BLADE_STACK,
      Stack.BOOTSTRAP_STACK,
      Stack.JQUERY_STACK,
      Stack.JAVASCRIPT_STACK,
      Stack.MVC_STACK,
    ],
  },
  {
    title: translate("projects.siriusWebpos.title"),
    company: translate("projects.siriusWebpos.company"),
    date: new Date(),
    description: translate("projects.siriusWebpos.description"),
    category: [
      translate("projects.siriusWebpos.category.admin"),
      translate("projects.siriusWebpos.category.webPos"),
    ],
    previewUrl: undefined,
    codeUrl: undefined,
    type: "confidential",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: translate("projects.siriusWebpos.imageName"),
    stack: [
      Stack.SPRING_BOOT_STACK,
      Stack.SPRING_API_STACK,
      Stack.SPRING_SECURITY_STACK,
      Stack.SPRING_JDBC_STACK,
      Stack.SPRING_API_STACK,
      Stack.VITE_STACK,
      Stack.JAVA_STACK,
      Stack.JWT_STACK,
      Stack.REACT_STACK,
      Stack.TYPESCRIPT_STACK,
      Stack.MOBX_STACK,
      Stack.ANT_DESIGN_STACK,
      Stack.I18N_STACK,
      Stack.AXIOS_STACK,
      Stack.CSS_STACK,
      Stack.LINUX_STACK,
      Stack.AZURE_STACK,
      Stack.AZURE_PIPELINE_AGENT_STACK,
      Stack.JEST_STACK,
      Stack.CYPRESS_STACK,
      Stack.CENTOS_STACK,
    ],
  },
  {
    title: translate("projects.unifiedYouth.title"),
    company: translate("projects.unifiedYouth.company"),
    date: new Date(),
    description: translate("projects.unifiedYouth.description"),
    category: [translate("projects.unifiedYouth.category.admin")],
    previewUrl: undefined,
    codeUrl: "https://github.com/orgs/Unified-Youth/repositories",
    type: "client",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: translate("projects.unifiedYouth.imageName"),
    stack: [
      Stack.SPRING_BOOT_STACK,
      Stack.SPRING_API_STACK,
      Stack.SPRING_JDBC_STACK,
      Stack.SPRING_SECURITY_STACK,
      Stack.SPRING_OAUTH_STACK,
      Stack.JUNIT_STACK,
      Stack.JAVA_STACK,
      Stack.VITE_STACK,
      Stack.REACT_STACK,
      Stack.SHAD_CN_STACK,
      Stack.TAILWIND_STACK,
      Stack.I18N_STACK,
      Stack.REACT_QUERY_STACK,
      Stack.AXIOS_STACK,
      Stack.AWS_STACK,
      Stack.FIGMA_STACK,
      Stack.VITEST_STACK,
      Stack.MICROSERVICES_STACK,
    ],
  },
  {
    title: translate("projects.countryScape.title"),
    company: translate("projects.countryScape.company"),
    date: new Date(),
    description: translate("projects.countryScape.description"),
    category: [translate("projects.countryScape.category.booking")],
    codeUrl: "https://github.com/javiergenepaul/country-scape",
    previewUrl: undefined,
    type: "personal",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: translate("projects.countryScape.imageName"),
    stack: [
      Stack.REACT_STACK,
      Stack.TYPESCRIPT_STACK,
      Stack.SHAD_CN_STACK,
      Stack.FIGMA_STACK,
      Stack.LANDING_PAGE_STACK,
      Stack.TAILWIND_STACK,
      Stack.NETLIFY_STACK,
      Stack.I18N_STACK,
    ],
  },
  {
    title: translate("projects.hoobank.title"),
    company: undefined,
    date: new Date(),
    description: translate("projects.hoobank.description"),
    category: [translate("projects.hoobank.category.landing")],
    previewUrl: "",
    codeUrl:
      "https://github.com/javiergenepaul/hoobank-react-tailwind-yt-tutorial",
    type: "tutorial",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: translate("projects.hoobank.imageName"),
    stack: [
      Stack.VITE_STACK,
      Stack.REACT_STACK,
      Stack.VITEST_STACK,
      Stack.TAILWIND_STACK,
      Stack.NETLIFY_STACK,
      Stack.LANDING_PAGE_STACK,
    ],
  },
  {
    title: translate("projects.iqmk.title"),
    company: translate("projects.iqmk.company"),
    date: new Date(),
    description: translate("projects.iqmk.description"),
    category: [translate("projects.iqmk.category.landing")],
    previewUrl: undefined,
    codeUrl: undefined,
    type: "confidential",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: translate("projects.iqmk.imageName"),
    stack: [
      Stack.HTML_STACK,
      Stack.TAILWIND_STACK,
      Stack.FIGMA_STACK,
      Stack.JQUERY_STACK,
      Stack.JAVASCRIPT_STACK,
      Stack.LANDING_PAGE_STACK,
    ],
  },
  {
    title: translate("projects.pawfectlyYours.title"),
    company: undefined,
    date: new Date(),
    description: translate("projects.pawfectlyYours.description"),
    category: [
      translate("projects.pawfectlyYours.category.ecommerce"),
      translate("projects.pawfectlyYours.category.landing"),
    ],
    codeUrl: "https://github.com/javiergenepaul/pawfectly-yours",
    previewUrl: undefined,
    type: "personal",
    image64: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?",
    imageName: translate("projects.pawfectlyYours.imageName"),
    stack: [
      Stack.SPRING_BOOT_STACK,
      Stack.SPRING_API_STACK,
      Stack.SPRING_JDBC_STACK,
      Stack.SPRING_OAUTH_STACK,
      Stack.SPRING_SECURITY_STACK,
      Stack.JWT_STACK,
      Stack.REACT_STACK,
      Stack.NEXT_UI_STACK,
      Stack.TYPESCRIPT_STACK,
      Stack.TAILWIND_STACK,
      Stack.HEROKU_STACK,
      Stack.MICROSERVICES_STACK,
    ],
  },
];

export const TYPE_ROLES: string[] = [
  translate("header.typeRole.fullStack"),
  translate("header.typeRole.reactTypescript"),
  translate("header.typeRole.springBoot"),
  translate("header.typeRole.uiuxAdvocate"),
  translate("header.typeRole.uiLibraryEnthusiasts"),
];
